rule all:
  input: "results/datasets.csv"

rule list_datasets:
  output: "results/datasets.csv"
  input: dynamic("data/datasets/dynverse/{dataset_id}/expression.csv")
  script:
    "modules/list_datasets.R"

rule datasets_dyntoy:
  input:
    "data/dataset_designs/dynverse/dyntoy/{dataset_id}.json"
  output:
    expression = "data/datasets/dynverse/{dataset_id}/expression.csv"
  script:
    "modules/dataset_generators/dyntoy/run.R"
    
rule dataset_design_dyntoy:
  output:
    dynamic("data/dataset_designs/dynverse/dyntoy/{dataset_id}.json")
  script:
    "modules/dataset_generators/dyntoy/create_design.R"
    
