language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x docs/deploy/build.sh

script:
  - docs/deploy/build.sh
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  on:
    branch: devel