language: r
cache: packages
pandoc_version: 1.19.2.1

install:
  - R -e 'setRepositories(ind = 1:2); devtools::install("package", dependencies = TRUE, upgrade = TRUE)'

before_script:
  - chmod +x docs/deploy/build.sh

script:
  - docs/deploy/build.sh
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: false
  on:
    branch: devel
  local-dir: docs/rendered